//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1WordWonder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public Word()
        {
            this.Entries = new HashSet<Entry>();
        }
    
        public int ID { get; set; }
        public string WordString { get; set; }
    
        public virtual ICollection<Entry> Entries { get; set; }
    }
}
